### ISSUE TITLE
No Files?

### ISSUE THREAD

**Issue by ParallelProductions** [SwagKartTheModder/mk64dsi#1]
Would love to give this a test but there's not files here but the readme..

**Comment by SwagKartTheModder** [comment]
Actually, I've made that GitHub page for a project that was scrapped long
ago. I thought I could do a homebrew app for the DSi in a more easily
accessible way but I can't.

**Comment by ParallelProductions** [comment]
Ahh i gotcha, yea porting really isn't easy I've tried many times. So many things that need to be changed in order to work properly.
